# Generated by Django 3.2 on 2026-02-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='token',
            field=models.TextField(),
        ),
    ]
