# Generated by Django 3.2 on 2026-02-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activator', '0002_auto_20260221_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('tariff', models.CharField(choices=[('month', 'Month'), ('year', 'Year')], max_length=10)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
    ]
