# Generated by Django 3.2 on 2026-02-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activator', '0003_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderKeyTg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('tg_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'OrderKeyTg',
                'verbose_name_plural': 'OrderKeyTgs',
                'ordering': ['-created_at'],
            },
        ),
    ]
